# Generated by Django 4.0.4 on 2022-04-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_book_user_remove_order_deliveredat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='Shipping',
        ),
    ]
