# Generated by Django 4.0.4 on 2022-05-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_shippingaddress_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='html',
            new_name='pdf',
        ),
    ]
