# Generated by Django 4.0.4 on 2022-05-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_html_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='epub',
            field=models.FileField(blank=True, null=True, upload_to='uploads/epub'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pdf'),
        ),
        migrations.AlterField(
            model_name='book',
            name='txt',
            field=models.FileField(blank=True, null=True, upload_to='uploads/txt'),
        ),
    ]
